export type ReviewProduct = {
  name: string;
  slug: string;
  image: string;
  bestFor: string;
  category: string;
  weight: string;
  capacity: string;
  summary: string;
  features: string[];
  pros: string[];
  cons: string[];
  amazon: string;
};

export type ProductDecision = {
  bestWhen: string[];
  considerAnotherWhen: string[];
  setupTip: string;
  searchIntent: string;
};

const tag = "rb10f-20";
const amazonSearch = (query: string) => `https://www.amazon.com/s?k=${encodeURIComponent(query)}&tag=${tag}`;

export const reviewProducts: ReviewProduct[] = [
  {
    name: "Full Focus Planner",
    slug: "full-focus-planner",
    image: "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best structured quarterly execution planner",
    category: "Goal Planners",
    weight: "Format: paper planner",
    capacity: "Verify edition, layout, and date range",
    summary: "A premium paper planner built around quarterly goals, weekly priorities, daily big-three planning, and reflection.",
    features: ["Quarterly goal structure", "Weekly preview", "Daily priority pages", "Habit and streak prompts", "Premium paper format"],
    pros: ["Excellent for founders who need a weekly review ritual", "Turns goals into daily priorities", "Feels intentional enough to keep on the desk"],
    cons: ["Paper-only workflow", "Higher cost than basic notebooks"],
    amazon: amazonSearch("Full Focus Planner"),
  },
  {
    name: "Clever Fox Planner Pro",
    slug: "clever-fox-planner-pro",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best all-in-one planning and habit tracking option",
    category: "Goal Planners",
    weight: "Format: undated paper planner",
    capacity: "Verify size, layout, and included stickers",
    summary: "A popular undated planner with goal-setting pages, weekly layouts, habit tracking, priorities, and reflection prompts.",
    features: ["Undated layout", "Monthly and weekly planning", "Habit tracker", "Goal map", "Elastic closure"],
    pros: ["Flexible start date", "Strong value for a complete planner", "Good for weekly accountability"],
    cons: ["Can feel busy for minimalists", "Paper size may not fit every bag"],
    amazon: amazonSearch("Clever Fox Planner Pro"),
  },
  {
    name: "Rocketbook Fusion Smart Reusable Notebook",
    slug: "rocketbook-fusion-smart-notebook",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best reusable notebook for digital capture",
    category: "Goal Planners",
    weight: "Format: reusable notebook",
    capacity: "Verify page count, size, and compatible pens",
    summary: "A reusable notebook that blends handwritten thinking with cloud capture for meeting notes, project plans, and weekly check-ins.",
    features: ["Reusable pages", "Cloud scanning", "Multiple planning templates", "Works with Pilot Frixion pens", "Portable format"],
    pros: ["Great for digital filing", "Reduces notebook clutter", "Useful for meetings and ideation"],
    cons: ["Requires compatible pens", "Not as tactile as premium paper"],
    amazon: amazonSearch("Rocketbook Fusion Smart Reusable Notebook"),
  },
  {
    name: "Ticktime Cube Pomodoro Timer",
    slug: "ticktime-cube-pomodoro-timer",
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best physical timer for deep work sprints",
    category: "Focus Timers",
    weight: "Format: digital cube timer",
    capacity: "Verify preset times and alarm modes",
    summary: "A simple physical timer that keeps focus blocks visible without forcing you to pick up your phone.",
    features: ["Flip-to-start presets", "Custom countdown", "Visual display", "Quiet or audible alerts", "Compact desk footprint"],
    pros: ["Reduces phone distractions", "Fast to start a sprint", "Good for Pomodoro or admin blocks"],
    cons: ["Another device to charge", "Preset workflow may not fit every schedule"],
    amazon: amazonSearch("Ticktime Cube Pomodoro Timer"),
  },
  {
    name: "Time Timer MOD Visual Timer",
    slug: "time-timer-mod-visual-timer",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best visual timer for time awareness",
    category: "Focus Timers",
    weight: "Format: analog visual timer",
    capacity: "Verify color, size, and time range",
    summary: "A visual countdown timer that makes remaining time obvious during writing, planning, coaching calls, and deep work.",
    features: ["Visual disappearing disk", "60-minute range", "Optional alert", "Desk-friendly size", "Interchangeable cases"],
    pros: ["Easy to understand at a glance", "Excellent for time boxing", "Does not require an app"],
    cons: ["Limited to short blocks", "Less precise than digital timers"],
    amazon: amazonSearch("Time Timer MOD Visual Timer"),
  },
  {
    name: "Sony WH-1000XM5 Noise-Canceling Headphones",
    slug: "sony-wh-1000xm5-headphones",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best premium focus headphones",
    category: "Focus Gear",
    weight: "Format: over-ear headphones",
    capacity: "Verify color, warranty, and current model",
    summary: "Premium noise-canceling headphones for founders who need a reliable focus bubble in offices, airports, and home workspaces.",
    features: ["Active noise canceling", "Bluetooth multipoint", "Long battery life", "Comfort-focused design", "Microphones for calls"],
    pros: ["Strong distraction control", "Useful for travel and shared workspaces", "Good call versatility"],
    cons: ["Premium price", "Over-ear fit is personal"],
    amazon: amazonSearch("Sony WH-1000XM5 noise canceling headphones"),
  },
  {
    name: "FlexiSpot Electric Standing Desk",
    slug: "flexispot-electric-standing-desk",
    image: "https://images.unsplash.com/photo-1593476550610-87baa860004a?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best adjustable desk foundation",
    category: "Desk Setup",
    weight: "Format: electric standing desk",
    capacity: "Verify desktop size and weight capacity",
    summary: "A height-adjustable desk foundation for entrepreneurs who spend long hours writing, selling, creating, and leading on video.",
    features: ["Electric height adjustment", "Memory presets", "Multiple desktop sizes", "Cable-management options", "Sit-stand workflow"],
    pros: ["Supports position changes", "Strong home-office upgrade", "Pairs well with monitor arms and lighting"],
    cons: ["Assembly required", "Desk size and stability vary by model"],
    amazon: amazonSearch("FlexiSpot electric standing desk"),
  },
  {
    name: "Ergotron LX Monitor Arm",
    slug: "ergotron-lx-monitor-arm",
    image: "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best monitor positioning upgrade",
    category: "Desk Setup",
    weight: "Format: adjustable monitor arm",
    capacity: "Verify monitor size and weight compatibility",
    summary: "A monitor arm that clears desk space and helps place the screen at a more workable height and distance.",
    features: ["Adjustable height", "Tilt and rotation", "Desk clamp or grommet mount", "Cable routing", "Premium arm tension"],
    pros: ["Improves screen positioning", "Frees desk space", "Durable professional feel"],
    cons: ["Requires compatible desk and monitor", "Premium price for an arm"],
    amazon: amazonSearch("Ergotron LX Monitor Arm"),
  },
  {
    name: "Logitech Brio 4K Webcam",
    slug: "logitech-brio-4k-webcam",
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best video-call credibility upgrade",
    category: "Remote Work Gear",
    weight: "Format: USB webcam",
    capacity: "Verify software and operating-system support",
    summary: "A polished webcam option for consultants, coaches, sales calls, webinars, and remote presentations.",
    features: ["4K-capable sensor", "Autofocus", "Field-of-view options", "Privacy cover on many bundles", "USB connectivity"],
    pros: ["Sharper video presence", "Useful for sales and coaching calls", "Works across many meeting platforms"],
    cons: ["Needs good lighting too", "Specs and bundles vary"],
    amazon: amazonSearch("Logitech Brio 4K Webcam"),
  },
  {
    name: "Elgato Key Light Air",
    slug: "elgato-key-light-air",
    image: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best compact lighting for video calls",
    category: "Remote Work Gear",
    weight: "Format: desk light panel",
    capacity: "Verify brightness, stand height, and app compatibility",
    summary: "A compact key light for making video calls, courses, and livestreams look more intentional without building a full studio.",
    features: ["Adjustable brightness", "Color temperature control", "Desk stand", "App control", "Diffused light"],
    pros: ["Improves face lighting", "Small desk footprint", "Good for calls and content"],
    cons: ["Requires desk space and power", "One light may not fix every room"],
    amazon: amazonSearch("Elgato Key Light Air"),
  },
  {
    name: "Atomic Habits by James Clear",
    slug: "atomic-habits-book",
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best habit systems book",
    category: "Business Books",
    weight: "Format: book/audiobook",
    capacity: "Verify edition and format",
    summary: "A practical habit-building book for entrepreneurs who need better defaults, not just more motivation.",
    features: ["Habit loop framing", "Environment design", "Identity-based habits", "Tracking ideas", "Practical examples"],
    pros: ["Clear and implementable", "Useful across business and personal routines", "Pairs well with planners"],
    cons: ["Requires practice, not just reading", "Some readers may know the concepts already"],
    amazon: amazonSearch("Atomic Habits James Clear"),
  },
  {
    name: "Deep Work by Cal Newport",
    slug: "deep-work-book",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best focus philosophy book",
    category: "Business Books",
    weight: "Format: book/audiobook",
    capacity: "Verify edition and format",
    summary: "A modern classic for protecting attention and creating high-value work in a distraction-heavy environment.",
    features: ["Deep work rules", "Distraction management", "Attention economics", "Scheduling ideas", "Professional examples"],
    pros: ["Excellent for knowledge workers", "Changes how you value focus", "Pairs with timers and time blocking"],
    cons: ["Some suggestions need adaptation", "Not a tactical planner by itself"],
    amazon: amazonSearch("Deep Work Cal Newport"),
  },
  {
    name: "The 12 Week Year",
    slug: "the-12-week-year-book",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best execution cadence book",
    category: "Business Books",
    weight: "Format: book/audiobook",
    capacity: "Verify edition and format",
    summary: "A focused execution system that compresses annual planning into shorter, more accountable cycles.",
    features: ["12-week execution cycle", "Lead measures", "Weekly scorekeeping", "Accountability rhythm", "Goal focus"],
    pros: ["Great for entrepreneurs who drift across too many goals", "Pairs well with planners", "Creates urgency without panic"],
    cons: ["Requires honest scoring", "Can be intense for overloaded teams"],
    amazon: amazonSearch("The 12 Week Year"),
  },
  {
    name: "The Invisible Organization by Mitch Russo",
    slug: "the-invisible-organization-book",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best virtual business operating model",
    category: "Business Books",
    weight: "Format: book/audiobook",
    capacity: "Verify edition and format",
    summary: "Mitch Russo's guide to building and leading a company without depending on a traditional office footprint.",
    features: ["Virtual company framework", "Remote-team operating ideas", "Leadership rhythm", "Communication model", "Entrepreneur case examples"],
    pros: ["Relevant for distributed teams", "Useful for founders reducing office dependency", "Pairs well with remote-work gear and video-call systems"],
    cons: ["Best for readers ready to redesign operations", "Not a quick desk accessory"],
    amazon: amazonSearch("The Invisible Organization Mitch Russo"),
  },
  {
    name: "Power Tribes by Mitch Russo",
    slug: "power-tribes-book",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best community and recurring-engagement model",
    category: "Business Books",
    weight: "Format: book/audiobook",
    capacity: "Verify edition and format",
    summary: "A book for entrepreneurs who want to turn audiences, customers, or members into more durable business communities.",
    features: ["Community-building framework", "Recurring engagement ideas", "Member experience focus", "Business-model thinking", "Implementation prompts"],
    pros: ["Useful for coaching, membership, and expert businesses", "Encourages retention-focused thinking", "Pairs well with accountability systems"],
    cons: ["Less relevant for purely transactional businesses", "Requires ongoing community execution"],
    amazon: amazonSearch("Power Tribes Mitch Russo"),
  },
  {
    name: "Licensing for Leverage by Mitch Russo",
    slug: "licensing-for-leverage-book",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best intellectual-property leverage guide",
    category: "Business Books",
    weight: "Format: book/audiobook",
    capacity: "Verify edition and format",
    summary: "A practical business book for entrepreneurs exploring how to package, license, and scale intellectual property.",
    features: ["Licensing model overview", "IP packaging ideas", "Leverage-focused strategy", "Offer design thinking", "Implementation considerations"],
    pros: ["Good fit for experts and creators", "Useful when a business has repeatable IP", "Supports leverage beyond one-to-one selling"],
    cons: ["Not a substitute for legal advice", "Requires a real asset or method to license"],
    amazon: amazonSearch("Licensing for Leverage Mitch Russo"),
  },
  {
    name: "Coach Elevation by Mitch Russo",
    slug: "coach-elevation-book",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best coaching-business growth system",
    category: "Business Books",
    weight: "Format: book/audiobook",
    capacity: "Verify edition and format",
    summary: "A business book for coaches who want clearer positioning, better delivery systems, and more reliable growth habits.",
    features: ["Coaching-business framework", "Positioning ideas", "Delivery-system thinking", "Growth cadence", "Client-experience focus"],
    pros: ["Relevant for consultants and coaches", "Connects strategy to execution", "Pairs well with planning and accountability tools"],
    cons: ["Best for service-business owners", "Requires implementation after reading"],
    amazon: amazonSearch("Coach Elevation Mitch Russo"),
  },
  {
    name: "Sacred Profits by Mitch Russo",
    slug: "sacred-profits-book",
    image: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best values-led leadership and profit book",
    category: "Business Books",
    weight: "Format: book/audiobook",
    capacity: "Verify edition and format",
    summary: "A leadership-minded business book for entrepreneurs who want profit, purpose, and decision-making to reinforce each other.",
    features: ["Values-led business thinking", "Leadership prompts", "Profit and purpose lens", "Decision-quality ideas", "Founder reflection"],
    pros: ["Useful for entrepreneurs making bigger choices", "Pairs with leadership and mindset reading", "Good fit for reflective weekly review"],
    cons: ["Not a tactical equipment purchase", "Best when paired with action planning"],
    amazon: amazonSearch("Sacred Profits Mitch Russo"),
  },
  {
    name: "Daily To-Do List Cards with Wooden Stand",
    slug: "daily-to-do-list-cards",
    image: "https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best visible daily priority card system",
    category: "Productivity Tools",
    weight: "Format: desk cards and stand",
    capacity: "Verify card size, count, and stand material",
    summary: "A simple analog desk system for keeping today's highest-value work visible without opening another app.",
    features: ["Undated task cards", "Desk stand", "Checklist format", "Low setup time", "Visible daily priority cue"],
    pros: ["Excellent for one-day focus", "Low-cost productivity reset", "Keeps priorities physically visible"],
    cons: ["No long-term archive unless saved", "Easy to outgrow if you need project management"],
    amazon: amazonSearch("daily to do list cards wooden stand productivity"),
  },
  {
    name: "Large 90-Day Wall Planner",
    slug: "large-90-day-wall-planner",
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best visible quarterly execution board",
    category: "Goal Achievement Systems",
    weight: "Format: wall calendar planner",
    capacity: "Verify dimensions, erasable surface, and mounting method",
    summary: "A large wall planner for making a 90-day push visible across campaigns, launches, sales activity, and weekly milestones.",
    features: ["Quarterly planning view", "Wall-mounted visibility", "Erasable surface options", "Milestone tracking", "Team or solo use"],
    pros: ["Makes deadlines hard to ignore", "Good for launch planning", "Supports weekly review conversations"],
    cons: ["Needs wall space", "Less portable than a notebook"],
    amazon: amazonSearch("90 day wall planner goals objective erasable calendar"),
  },
  {
    name: "Personal Kanban Whiteboard",
    slug: "personal-kanban-whiteboard",
    image: "https://images.unsplash.com/photo-1600267204091-5c1ab8b10c02?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best visual workflow board",
    category: "Productivity Tools",
    weight: "Format: magnetic or dry-erase board",
    capacity: "Verify board size, mounting hardware, and included accessories",
    summary: "A visible Kanban board helps entrepreneurs limit work in progress and see what is waiting, active, blocked, and done.",
    features: ["Dry-erase surface", "Kanban workflow layout", "Magnetic options", "Wall or rolling formats", "Project visibility"],
    pros: ["Great for reducing scattered priorities", "Works for solo or small teams", "Easy to review at a glance"],
    cons: ["Requires regular maintenance", "Can become cluttered without work-in-progress limits"],
    amazon: amazonSearch("personal Kanban whiteboard productivity"),
  },
  {
    name: "OKR Workbook and Goal Journal",
    slug: "okr-workbook-goal-journal",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best objective and key-result planning workbook",
    category: "Goal Achievement Systems",
    weight: "Format: workbook or journal",
    capacity: "Verify format, page count, and planning horizon",
    summary: "An OKR workbook gives founders a structured place to define objectives, key results, initiatives, and review cadence.",
    features: ["Objective prompts", "Key-result tracking", "Weekly review space", "Initiative planning", "Scorecard sections"],
    pros: ["Connects goals to measurable outcomes", "Helpful for founder self-management", "Pairs well with quarterly planning"],
    cons: ["Can be too formal for tiny projects", "Requires honest metrics"],
    amazon: amazonSearch("OKR workbook goal journal"),
  },
  {
    name: "Ergonomic Office Chair",
    slug: "ergonomic-office-chair",
    image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best long-session seating upgrade",
    category: "Desk Setup",
    weight: "Format: adjustable office chair",
    capacity: "Verify height range, weight capacity, and return policy",
    summary: "A supportive chair is one of the least glamorous but most important purchases for entrepreneurs who sit through long creation and call blocks.",
    features: ["Adjustable height", "Lumbar support", "Arm adjustments on many models", "Rolling base", "Breathable or cushioned options"],
    pros: ["Can reduce workspace friction", "Important for long call days", "Pairs with standing desks and monitor arms"],
    cons: ["Fit is highly personal", "Good chairs can be expensive"],
    amazon: amazonSearch("ergonomic office chair home office"),
  },
  {
    name: "Portable Laptop Monitor",
    slug: "portable-laptop-monitor",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best travel screen-space upgrade",
    category: "Remote Work Gear",
    weight: "Format: portable external display",
    capacity: "Verify screen size, USB-C/HDMI support, and power needs",
    summary: "A portable monitor gives remote entrepreneurs more working room for research, calls, dashboards, and writing when away from the main desk.",
    features: ["Portable display", "USB-C options", "Foldable cover stands", "Lightweight travel format", "Second-screen workflow"],
    pros: ["Great for travel work", "Improves laptop-only productivity", "Useful for presentations and analysis"],
    cons: ["Needs cable compatibility", "Brightness and stands vary"],
    amazon: amazonSearch("portable monitor for laptop remote work"),
  },
  {
    name: "Adjustable Laptop Stand",
    slug: "adjustable-laptop-stand",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best simple posture and call-framing upgrade",
    category: "Remote Work Gear",
    weight: "Format: folding or desktop laptop stand",
    capacity: "Verify laptop size support and stability",
    summary: "A laptop stand can raise the camera and screen to a more workable height, especially for video calls and temporary workspaces.",
    features: ["Adjustable height options", "Foldable travel models", "Ventilation gaps", "Desk-friendly footprint", "Pairs with external keyboard"],
    pros: ["Low-friction desk improvement", "Better video-call framing", "Portable options available"],
    cons: ["Usually needs separate keyboard and mouse", "Stability varies by model"],
    amazon: amazonSearch("adjustable laptop stand remote work"),
  },
  {
    name: "USB Podcast Microphone",
    slug: "usb-podcast-microphone",
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best audio credibility upgrade",
    category: "Remote Work Gear",
    weight: "Format: USB microphone",
    capacity: "Verify connector, stand, gain controls, and software support",
    summary: "A USB microphone can make sales calls, webinars, interviews, and coaching sessions feel more professional than laptop audio.",
    features: ["USB connectivity", "Desk stand or boom-arm support", "Mute controls on many models", "Podcast and meeting use", "Directional pickup patterns"],
    pros: ["Clearer speaking presence", "Useful for content and calls", "Often easier than full audio interfaces"],
    cons: ["Needs good placement", "Can pick up room noise without setup care"],
    amazon: amazonSearch("USB podcast microphone video calls entrepreneurs"),
  },
  {
    name: "Blue-Light Blocking Glasses",
    slug: "blue-light-blocking-glasses",
    image: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best screen-heavy evening work accessory",
    category: "Focus Gear",
    weight: "Format: glasses",
    capacity: "Verify lens tint, fit, and intended use",
    summary: "Blue-light glasses are a low-friction accessory to compare if late screen work is part of your routine, while remembering that habits and lighting matter too.",
    features: ["Screen-use accessory", "Clear or tinted lens options", "Multiple frame styles", "Work and travel formats", "Low setup friction"],
    pros: ["Easy to try", "Pairs with evening shutdown routines", "Useful for screen-heavy workers to compare"],
    cons: ["Benefits vary by person", "Not a substitute for sleep hygiene or breaks"],
    amazon: amazonSearch("blue light blocking glasses computer work"),
  },
  {
    name: "Sleep Tracker Ring or Wearable",
    slug: "sleep-tracker-wearable",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best recovery-awareness tool",
    category: "Personal Performance",
    weight: "Format: ring, watch, or wearable tracker",
    capacity: "Verify sizing, battery, subscription, and app compatibility",
    summary: "A sleep tracker can help entrepreneurs notice patterns in rest, recovery, and schedule choices that affect work quality.",
    features: ["Sleep trend tracking", "Wearable format", "Mobile app dashboards", "Recovery or readiness signals on some models", "Long-term pattern visibility"],
    pros: ["Makes rest patterns visible", "Useful for busy travel schedules", "Can support better shutdown habits"],
    cons: ["Not medical diagnosis", "Some features may require subscriptions"],
    amazon: amazonSearch("sleep tracker ring wearable"),
  },
  {
    name: "Smart Hydration Bottle",
    slug: "smart-hydration-bottle",
    image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best simple energy-rhythm cue",
    category: "Personal Performance",
    weight: "Format: bottle or reminder bottle",
    capacity: "Verify size, cleaning instructions, and charging requirements if smart",
    summary: "A hydration bottle with time markers or reminders can create a simple daily cue for entrepreneurs who skip basic routines during busy work blocks.",
    features: ["Time-marker or smart reminder options", "Desk and travel formats", "Reusable bottle", "Multiple capacities", "Routine cue"],
    pros: ["Low-effort daily support", "Visible reminder during focus blocks", "Pairs with morning and afternoon routines"],
    cons: ["Smart versions may need charging", "Cleaning requirements vary"],
    amazon: amazonSearch("smart hydration bottle time marker"),
  },
  {
    name: "Meditation and Breathing Device",
    slug: "meditation-breathing-device",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80",
    bestFor: "Best reset tool before high-stakes work",
    category: "Personal Performance",
    weight: "Format: guided device or wearable",
    capacity: "Verify app requirements, subscription, and training style",
    summary: "A meditation or breathing device can create a structured reset before sales calls, writing blocks, and difficult decisions.",
    features: ["Guided breathing", "App-supported sessions on some models", "Portable format", "Stress-reset workflow", "Routine prompts"],
    pros: ["Useful transition ritual", "Good before calls or deep work", "Can support consistency for beginners"],
    cons: ["Not necessary for people who already meditate", "Some tools require subscriptions"],
    amazon: amazonSearch("meditation breathing device focus"),
  },
];

export function getReviewProductBySlug(slug: string) {
  return reviewProducts.find((product) => product.slug === slug);
}

export function getProductDecision(product: ReviewProduct): ProductDecision {
  const category = product.category.toLowerCase();

  if (category.includes("book")) {
    return {
      bestWhen: ["You want a proven mental model before buying more tools.", "You will translate the idea into a weekly habit or scorecard.", "You prefer reading or listening before changing systems."],
      considerAnotherWhen: ["You need a physical planning tool immediately.", "You already have the concept and need execution infrastructure."],
      setupTip: "Choose one chapter or idea and turn it into a weekly review question, not just a highlight.",
      searchIntent: "productivity books for entrepreneurs",
    };
  }

  if (category.includes("focus")) {
    return {
      bestWhen: ["You need phone-free focus blocks.", "You work in a noisy or interruption-heavy environment.", "You want an external cue to start and stop deep work."],
      considerAnotherWhen: ["Your bigger issue is unclear priorities.", "You need ergonomic desk changes before focus accessories."],
      setupTip: "Pair the tool with a written outcome for each work sprint so the session has a finish line.",
      searchIntent: "focus tools for deep work",
    };
  }

  if (category.includes("desk") || category.includes("remote")) {
    return {
      bestWhen: ["You spend many hours at a screen.", "Your work depends on video calls, writing, sales, or content creation.", "You want fewer friction points in a daily workspace."],
      considerAnotherWhen: ["You have not measured the desk, monitor, or room constraints.", "You need a budget-friendly starter setup first."],
      setupTip: "Measure your desk, monitor weight, lighting angle, and cable path before buying hardware.",
      searchIntent: "entrepreneur home office setup",
    };
  }

  return {
    bestWhen: ["You want a weekly review ritual.", "You need to turn goals into daily priorities.", "You like writing plans by hand."],
    considerAnotherWhen: ["You need team collaboration features.", "You already live completely inside a digital task manager."],
    setupTip: "Block the same 30 minutes every week to review goals, choose priorities, and reset the next sprint.",
    searchIntent: "goal planner for entrepreneurs",
  };
}

export function getRelatedProducts(product: ReviewProduct, limit = 3) {
  return reviewProducts
    .filter((candidate) => candidate.slug !== product.slug)
    .sort((a, b) => (a.category === product.category ? 0 : 1) - (b.category === product.category ? 0 : 1))
    .slice(0, limit);
}

export function getProductFaqs(product: ReviewProduct) {
  return [
    {
      question: `What should I verify before buying ${product.name}?`,
      answer: "Confirm the current model, edition, size, compatibility, return policy, warranty, and whether the tool fits your actual workflow before buying.",
    },
    {
      question: `Will ${product.name} create a breakthrough by itself?`,
      answer: "No. The product can reduce friction, but the breakthrough comes from a repeatable cadence: clear priorities, focused work, review, and accountability.",
    },
    {
      question: "Why does ResultsBreakthrough link to Amazon search results?",
      answer: "Amazon inventory, bundles, editions, and prices change. Search links with the affiliate tag let you compare the current available versions.",
    },
  ];
}
