export const articleSources = [
  {"id": "editorial-d5ac2c381c4c76", "title": "2020 Scrum Guide", "organization": "scrumguides.org", "url": "https://scrumguides.org/scrum-guide.html"},
  {"id": "editorial-4f796a52371bae", "title": "meta-analysis by Harkin and colleagues", "organization": "www.apa.org", "url": "https://www.apa.org/pubs/journals/releases/bul-bul0000025.pdf"},
  {"id": "editorial-cc364db673741b", "title": "SBA business management resources", "organization": "www.sba.gov", "url": "https://www.sba.gov/counseling/manage-your-business/"},
  {"id": "editorial-77da557a62597b", "title": "CDC evaluation framework", "organization": "www.cdc.gov", "url": "https://www.cdc.gov/evaluation/php/evaluation-framework/index.html"},
  {"id": "editorial-3e2a8d9350c3db", "title": "SBA manage your business", "organization": "www.sba.gov", "url": "https://www.sba.gov/business-guide/manage-your-business"},
  {"id": "editorial-e6241316320a10", "title": "NIOSH organization of work", "organization": "www.cdc.gov", "url": "https://www.cdc.gov/niosh/learning/safetyculturehc/module-2/6.html"},
  {"id": "editorial-8d33902a5c9491", "title": "CDC policy evaluation framework", "organization": "www.cdc.gov", "url": "https://www.cdc.gov/policy/php/evaluation/index.html"},
  {"id": "editorial-56d34b7966f45e", "title": "Research recommendations on planning interventions", "organization": "pubmed.ncbi.nlm.nih.gov", "url": "https://pubmed.ncbi.nlm.nih.gov/26892502/"},
  {
    id: "cleverfox-official",
    title: "Clever Fox Planner",
    organization: "Clever Fox",
    url: "https://cleverfoxplanner.com/",
  },
  {
    id: "ergotron-home-office",
    title: "Home Office Ergonomics",
    organization: "Ergotron",
    url: "https://www.ergotron.com/en-us/markets/office/home-office",
  },
  {
    id: "techradar-standing-desks",
    title: "Best Standing Desk",
    organization: "TechRadar",
    url: "https://www.techradar.com/news/best-standing-desk",
  },
  {
    id: "strategist-planners",
    title: "Best Planners",
    organization: "New York Magazine Strategist",
    url: "https://nymag.com/strategist/article/best-planners.html",
  },
  {
    id: "businessinsider-planners",
    title: "Best Planners",
    organization: "Business Insider",
    url: "https://www.businessinsider.com/guides/tech/best-planner",
  },
  {
    id: "actionablebooks-productivity",
    title: "Best Productivity Books",
    organization: "Actionable Books",
    url: "https://www.actionablebooks.com/guides/best-productivity-books/",
  },
  {
    id: "amazon-ticktime",
    title: "Ticktime Cube Pomodoro Timer",
    organization: "Amazon",
    url: "https://www.amazon.com/s?k=Ticktime+Cube+Pomodoro+Timer",
  },
  {
    id: "amazon-12-week-year",
    title: "The 12 Week Year",
    organization: "Amazon",
    url: "https://www.amazon.com/12-Week-Year-Others-Months/dp/B08XLLDYH7",
  },
  {
    id: "atomic-habits",
    title: "Atomic Habits",
    organization: "James Clear",
    url: "https://jamesclear.com/atomic-habits",
  },
  {
    id: "cal-newport-deep-work",
    title: "Deep Work",
    organization: "Cal Newport",
    url: "https://www.calnewport.com/books/deep-work/",
  },
  {
    id: "mitch-russo-books",
    title: "Books by Mitch Russo on Coaching, Certification and Licensing",
    organization: "Mitch Russo",
    url: "https://mitchrusso.com/books/",
  },
];
